add_newline = false
format = "$env_var$directory$git_branch$git_status$character"

[env_var.CAIGED_WINDOW]
format = " [$env_value]($style)"
style = "bold yellow"

[directory]
style = "cyan"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
style = "blue"
format = " [$branch]($style)"

[git_status]
style = "yellow"
format = "[$all_status$ahead_behind]($style)"

[character]
success_symbol = ">"
error_symbol = ">"
